<a href="https://colab.research.google.com/github/SofiiaBobr/goit_machine_learning/blob/main/tree/main/np.1/numpy_tasks_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнє завдання: NumPy та Лінійна алгебра


## Задача 1. Робота з зображеннями як з матрицями
**Умова**
Цифрові зображення у комп'ютері зберігаються як масиви чисел (матриці). Будь-яке чорно-біле зображення для комп'ютера — це просто матриця чисел, де кожне число — яскравість пікселя від 0 до 255. Редагування зображень базується на арифметичних операціях з цими матрицями.

Ви працюєте з фрагментом зображення розміром $3 \times 3$ пікселі.

Дано матрицю зображення $M$ та матрицю накладеного ефекту $E$:
$M = \begin{pmatrix} 100 & 150 & 200 \\ 50 & 100 & 150 \\ 0 & 50 & 100 \end{pmatrix}, \quad E = \begin{pmatrix} 20 & 30 & 40 \\ 10 & 20 & 30 \\ 5 & 10 & 15 \end{pmatrix}$

Необхідно реалізувати три алгоритми обробки:
• **Зміна контрасту.** Необхідно зменшити яскравість зображення $M$. Це множення матриці на скаляр (число) $\lambda$. Кожен елемент матриці множиться на це число 0.5
• **Корекція яскравості.** Це додавання скаляра $c$ до матриці $M$. Число додається до кожного елемента матриці. Додайте до зображення $M$ число 25. Це збільшить яскравість кожного пікселя на 25.
• **Змішування (Blending).** Ми створюємо нове зображення, змішуючи оригінал та ефект у певній пропорції. Для цього створи нове зображення як лінійну комбінацію: $0.8 \cdot M + 0.2 \cdot E$. Це імітує прозорість ефекту.

**Завдання:**
1. Обчисліть це аналітично та покажіть проміжні кроки.
2. Використовуючи бібліотеку `numpy`, напишіть програму, що виконує ті самі операції та перевіряє твої аналітичні обчислення. Виведіть на екран результати обчислень для кожного фільтра.


In [1]:
import numpy as np

M = np.array([
    [100, 150, 200],
    [50, 100, 150],
    [0, 50, 100]
])

E = np.array([
    [20, 30, 40],
    [10, 20, 30],
    [5, 10, 15]
])

print(f"Оригінальна матриця:\n{M}")

#Операція один. Зміна контрасту

contrast_matrix = 0.5*M
print(f"Зміна контрасту (M*0,5):\n{contrast_matrix}")


Оригінальна матриця:
[[100 150 200]
 [ 50 100 150]
 [  0  50 100]]
Зміна контрасту (M*0,5):
[[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]


In [2]:
#Операція два. Корекція яскравості.
britness_matrix = 25 + M
print(f"Зміна яскравості (25 + M):\n{britness_matrix}")



Зміна яскравості (25 + M):
[[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]


In [3]:
#Операція три. Змішування.
blend_matrix = 0.8*M+0.2*E
print(f"Змішування (0.8⋅M+0.2⋅E):\n{blend_matrix}")

Змішування (0.8⋅M+0.2⋅E):
[[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]


## Задача 2. Пошук схожих фільмів
**Умова**
Рекомендаційні системи як Netflix або YouTube часто представляють користувачів та контент у вигляді векторів.
Є профіль користувача — це вектор інтересів до жанрів `[Екшн, Комедія, Драма]`.

Також є три фільми $A, B, C$, кожен з яких має таку ж структуру характеристик.
Вектор профілю користувача: $\mathbf{u} = (8, 2, 5)$

Та три фільмів.
• Фільм A (Action Movie): $\mathbf{v}_A = (9, 1, 2)$
• Фільм B (Comedy Movie): $\mathbf{v}_B = (1, 9, 8)$
• Фільм C (Drama Movie): $\mathbf{v}_C = (7, 2, 6)$

Ваша задача — знайти фільм, який найбільше підходить користувачу, порівнявши вектори їхніх характеристик.

Нагадуємо, чим менший кут між цими векторами у багатовимірному просторі, тим більше схожі об'єкти. Мірою цієї схожості є **косинусна подібність**. Вона показує, наскільки вектори "дивляться" в один бік. Значення коливається від -1 (протилежні) до 1 (ідентичні).

Формула косинусної подібності: $\cos \theta = \frac{\mathbf{u} \cdot \mathbf{v}}{\|\mathbf{u}\| \cdot \|\mathbf{v}\|}$
де $\mathbf{u} \cdot \mathbf{v}$ — скалярний добуток, а $\|\mathbf{u}\|, \|\mathbf{v}\|$ — довжина (норма) вектора.

**Аналітична частина розв'язку.**
1. Обчисліть аналітично норму вектора користувача $\|\mathbf{u}\|$.
2. Обчисліть схожість (similarity score) профілю користувача з кожним із трьох фільмів.
3. Порівняйте отримані значення та визначте, який фільм має найвищий бал схожості.

**Програмна частина розв'язку.**
Використовуючи бібліотеку `numpy` напишіть програму та виконайте наступні кроки:
1. Створіть вектор профілю користувача та вектори фільмів
2. Реалізуйте функцію косинусної схожості за формулою
3. Обчисліть схожість для кожного фільму
4. Виведіть на екран коефіцієнти схожості для кожного фільму та назву фільму, вектор якого має найбільше значення косинусної подібності.
5. Перевірте себе та порівняйте з аналітичними обчисленнями, щоб вони збігалися


In [4]:

u = np.array([8, 2, 5])
a = np.array([9, 1, 2])
b = np.array([1, 9, 8])
c = np.array([7, 2, 6])

list_vect = [a, b, c]
list_name_films = ["Action Movie", "Comedy Movie", "Drama Movie" ]

In [5]:
def cos_similarity(v1, v2):
  dot_product = np.dot(v1,v2)
  norm_v1 = np.linalg.norm(v1)
  norm_v2 = np.linalg.norm(v2)

  return dot_product/(norm_v1*norm_v2)

In [6]:
movi_sim = {}
for n, v in zip(list_name_films, list_vect):
  similarity_score = cos_similarity(u, v)
  print(f"Схожість з фільмом {n} {similarity_score:.3f}")
  movi_sim[n] = similarity_score

# Find the film with the highest similarity
best_film = max(movi_sim, key=movi_sim.get)
print(f"\nФільм, який найбільше підходить користувачу: {best_film} (Схожість: {movi_sim[best_film]:.3f})")

Схожість з фільмом Action Movie 0.939
Схожість з фільмом Comedy Movie 0.566
Схожість з фільмом Drama Movie 0.989

Фільм, який найбільше підходить користувачу: Drama Movie (Схожість: 0.989)


Задача 3



Ви керуєте цехом зі збірки FPV-дронів.
У вас три моделі: "Розвідник" $x_1$, "Камікадзе" $x_2$ та важкий "Вантажний" дрон $x_3$.

Кожен із них потребує різного набору комплектуючих: моторів, польотних контролерів та акумуляторів.

В кінці зміни приходить звіт про загальні витрати деталей, але через збій у системі ти втратив дані про те, скільки саме дронів кожного типу було зібрано.

Це класична задача на відновлення даних, яка вирішується через систему лінійних рівнянь $A\mathbf{x} = \mathbf{b}$.

Відомі витрати на один дрон, це матриця $A$, де стовпці — це типи дронів:
• "Розвідник": 4 мотори, 1 контролер, 1 акумулятор.
• "Камікадзе": 4 мотори, 1 контролер, 2 акумулятори.
• "Вантажний": 6 моторів, 2 контролери, 4 акумулятори.

Всього за зміну було витрачено вектор $\mathbf{b}$:
• 460 моторів
• 130 контролерів
• 240 акумуляторів

Використовуючи бібліотеку `numpy`, напишіть програму та виконайте наступні кроки:
1. Сформуйте матрицю коефіцієнтів $A$ та вектор вільних членів $\mathbf{b}$.
2. Перед розв'язанням перевірте, чи має система єдиний розв'язок. Для цього обчисліть визначник матриці $A$ за допомогою функції `np.linalg.det(A)`. Якщо він не дорівнює нулю — розв'язок існує.
3. Розв'яжіть систему за допомогою `np.linalg.solve(A, b)` і знайдіть вектор $\mathbf{x}$. Це буде кількість зібраних дронів кожного типу.
4. Виконайте перевірку правильності розрахунків: перемножте матрицю $A$ на знайдений вектор $\mathbf{x}$. Результат має збігатися з вектором $\mathbf{b}$.
5. Виведіть кількість дронів кожного типу та результати перевірки.


In [8]:

A = np.array([
    [4, 4, 6],
    [1, 1, 2],
    [1, 2, 4]
])

b = np.array([460, 130, 240])




In [9]:
det_A = np.linalg.det(A)
print(f'детермінант матриці А: {det_A}')

детермінант матриці А: -2.0


In [10]:
if np.isclose(det_A, 0):
  print("Однозначного розвʼязку не існує, бо детермінант рівний 0")
else:
  x = np.linalg.solve(A, b)
  x = np.round(x).astype(int)
  print(f'Дронів "розвідників": {x[0]}')
  print(f'Дронів "камікадзе": {x[1]}')
  print(f'Дронів "Вантажний": {x[2]}')

Дронів "розвідників": 20
Дронів "камікадзе": 50
Дронів "Вантажний": 30


In [12]:
b_chack = np.dot(A, x)
if np.allclose(b, b_chack):
  print(f'Перевірка пройдена успішно')
else:
  print(f'Перевірку провалено')

Перевірка пройдена успішно


## Задача 4. Прогноз тренду
**Умова**
При моніторингу IT-інфраструктури дані часто надходять із шумом.
Навантаження на CPU сервера може коливатися, але загальний тренд вказує на поступове зростання.
Щоб передбачити, коли сервер досягне критичного навантаження, потрібно побудувати лінію тренду $y = kx + b$.

Оскільки точки не лежать ідеально на одній прямій, точного розв'язку системи не існує, тому використовується метод найменших квадратів (МНК).

Дано виміри завантаження CPU $y$ протягом 5 годин $t$:
• Час $t = [1, 2, 3, 4, 5]$
• Навантаження $y = [22, 28, 37, 45, 53]$

Використовуючи бібліотеку `numpy`, напишіть програму та виконайте наступні кроки:
1. Сформуйте матрицю $A$. Пам'ятайте, що для знаходження вільного члена $b$ матриця повинна містити стовпчик зі значень $t$ та стовпчик з одиниць.
2. Знайдіть коефіцієнти прямої $k$ та $b$ за допомогою функції `np.linalg.lstsq(A, y)`. Ця функція повертає найкращий наближений розв'язок.
3. Використовуючи знайдені коефіцієнти, обчисліть прогнозоване навантаження на **6-ту годину** за формулою $\hat{y} = k \cdot 6 + b$.
4. Виведіть рівняння отриманого тренду та прогноз.


**Кроки:**
1. Обчислити $A^T A$
2. Обчислити $A^T \mathbf{y}$
3. Розв'яжіть систему через `np.linalg.solve()`
4. Порівняйте результат з `lstsq` — вони мають збігатися


In [13]:
t = np.array([1, 2, 3, 4, 5])

y = np.array([22, 28, 37, 45, 53])

A = np.vstack([t, np.ones(len(t))]).T
print(f'Матриця А: {A}')


Матриця А: [[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]]


In [14]:
coeff, rs, rank, s =  np.linalg.lstsq(A, y, rcond=None)
k, b = coeff
print(f'Рівняння тренду: y={k:.2f}*t+{b:.2f}')




Рівняння тренду: y=7.90*t+13.30


In [20]:
t_fut = 6
y_pred = k*t_fut + b
print(f'Прогнозованк навантаження на {t_fut} годину {y_pred}')

Прогнозованк навантаження на 6 годину 60.7


In [21]:
AtA = np.dot(A.T, A)
Aty = np.dot(A.T, y)
x_normal = np.linalg.solve(AtA, Aty)
k_norm, b_norm = x_normal
print(f'Рівняння тренду: y={k_norm:.2f}*t+{b_norm:.2f}')


Рівняння тренду: y=7.90*t+13.30
